# Generated by Django 5.2.16 on 2026-07-13 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_video', models.FileField(upload_to='videos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('ready_for_review', 'Ready for Review'), ('rendering', 'Rendering'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('words_per_line', models.PositiveSmallIntegerField(default=3)),
                ('caption_position', models.CharField(choices=[('bottom', 'Bottom'), ('top', 'Top')], default='bottom', max_length=10)),
                ('whisper_model_size', models.CharField(choices=[('tiny', 'Tiny'), ('base', 'Base'), ('small', 'Small'), ('medium', 'Medium')], default='small', max_length=10)),
                ('caption_data', models.JSONField(blank=True, help_text='List of {id, text, start, end} caption chunks produced by Whisper (word-grouped), editable by the user.', null=True)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='output/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
