# Generated by Django 5.2.16 on 2026-07-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionjob',
            name='words_per_line',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
