# Generated by Django 5.2.16 on 2026-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captions', '0002_alter_captionjob_words_per_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='captionjob',
            name='name',
            field=models.CharField(default='Untitled Project', max_length=255),
        ),
        migrations.AddField(
            model_name='captionjob',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
