# Generated by Django 5.2.16 on 2026-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captions', '0003_captionjob_name_captionjob_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='captionjob',
            name='caption_offset',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captionjob',
            name='caption_style',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captionjob',
            name='edit_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
